### ISSUE TITLE
Deploy a Test-Version publicly available

### ISSUE THREAD

**Issue by unclearParadigm** [agrippa1994/vacation-planner#19]
#### Feature-Request

as a Fanboy of your software, I'd really love to see a deployment of the whole application to a public-facing server, so that I can play around with the vacation-planner. It'd be really cool.

you guys are awesome!

**Comment by agrippa1994** [comment]
Thanks for your interests in our software! We have a public beta available at https://vacation.mani94.space/

Please feel free to play around and give us some feedback ;)

**Comment by unclearParadigm** [comment]
Thank you kind sir! The Vacation-Planner is super awesome!!!
